on:
  cli:
    init:
      sha: ${{ event.git.sha }}
      publish: false

base:
  image: ubuntu:24.04
  config: rwx/base 1.0.0

tasks:
  - key: code
    call: git/clone 2.0.3
    with:
      preserve-git-dir: true
      repository: https://github.com/rwx-cloud/packages.git
      ref: ${{ init.sha }}
      github-token: ${{ github['rwx-cloud'].token }}

  - key: timestamp
    use: code
    run: |
      latest_timestamp=$(git ls-files -z $DIRECTORY | xargs -0 -n1 -I{} -- git log -1 --date=format:"%Y%m%d%H%M" --format="%ad" {} | sort | tail -n 1)
      echo -n "$latest_timestamp" | tee $RWX_VALUES/timestamp
    env:
      DIRECTORY: ${{ init.directory }}

  - key: build
    use: code
    run: |
      cd $DIRECTORY
      if [[ -f build/run.sh ]]; then
        echo "Running build script"
        ./build/run.sh
      else
        echo "No build script"
      fi
    env:
      DIRECTORY: ${{ init.directory }}

  - key: package
    use: [build, timestamp]
    call: d2bb517b1d8aeba18543229ac45446d2518e9fbc1a99bcf8bf1cbfa1a374fa1b
    with:
      directory: ${{ init.directory }}
      rwx-access-token: ${{ vaults.mint_leaves_development.secrets.RWX_ACCESS_TOKEN }}
      timestamp: ${{ tasks.timestamp.values.timestamp }}

  - key: generate-test
    use: [code, package]
    run: |
      echo '[{"image": "ubuntu:24.04", "config": "rwx/base 1.0.0"}]' | tee $RWX_VALUES/base-images
      cp "$DIRECTORY/.rwx/test.yml" test-run.yml
    env:
      DIRECTORY: ${{ init.directory }}
    outputs:
      artifacts:
        - key: test-run
          path: test-run.yml

  - key: test
    call: ${{ tasks.generate-test.artifacts.test-run }}
    parallel:
      values: ${{ tasks.generate-test.values.base-images }}
    init:
      package-digest: ${{ tasks.package.values.digest }}
      base-image: ${{ parallel.image }}
      base-config: ${{ parallel.config }}

  - key: publish
    if: ${{ init.publish }}
    after: test
    run: |
      curl \
        --request POST \
        --fail-with-body \
        --header "Authorization: Bearer $RWX_ACCESS_TOKEN" \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/json' \
        --data '{ "digest": "${{ tasks.package.values.digest }}" }' \
        https://cloud.rwx.com/mint/api/leaves/publish
    env:
      RWX_ACCESS_TOKEN:
        cache-key: excluded
        value: ${{ vaults.mint_leaves_development.secrets.RWX_ACCESS_TOKEN }}
